server:
  port: 9999

spring:
  application:
    name: rampup-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
    gateway:
      routes[0]:
        id: nacos-auth-route
        uri: lb://rampup-auth
        predicates[0]:
          name: Path
          args[pattern]: /auth1/**
        filters[0]: StripPrefix=1
      routes[1]:
        id: nacos-client-route
        uri: lb://rampup-client
        predicates[0]:
          name: Path
          args[pattern]: /client1/**
        filters[0]: StripPrefix=1
      routes[2]:
        id: nacos-client2-route
        uri: lb://rampup-client2
        predicates[0]:
          name: Path
          args[pattern]: /client2/**
        filters[0]: StripPrefix=1
      routes[3]:
        id: nacos-client3-route
        uri: lb://rampup-client3
        predicates[0]:
          name: Path
          args[pattern]: /client3/**
        filters[0]: StripPrefix=1
      routes[4]:
        id: magus-client-route
        uri: lb://magus-client
        predicates[0]:
          name: Path
          args[pattern]: /client/**
        filters[0]: StripPrefix=1
      routes[5]:
        id: magus-auth-route
        uri: lb://magus-auth
        predicates[0]:
          name: Path
          args[pattern]: /auth/**
        filters[0]: StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8001  #认证中心端点，作为资源端的配置

security:
  ignore:
    urls: #配置白名单路径
      - "/favicon.ico"
      - "/auth/oauth2/*"
