#server:
#  port: 8083
#
#spring:
#  application:
#    name: rampup-client3
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}


server:
  port: 8085

spring:
  application:
    name: magus-client
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
#        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8001/oauth2/jwks
